### ISSUE TITLE
Build script failing for some reason?

### ISSUE THREAD

**Issue by someguy20336** [someguy20336/TypeRight#8]
Not sure why, but the build script is failing even though the scripts generated from the extension work just fine.  Need to troubleshoot this more...

**Comment by someguy20336** [comment]
Here is the exception I see.  Only mildly helpful...

Warning		An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary'2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary'2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()

**Comment by someguy20336** [comment]
Found this: seems to be some sort of [Roslyn issue](https://github.com/dotnet/roslyn/issues/24991)

Possibly due to two Nuget packages referencing the same package or something?  Need to try that out later on a simple project.

**Comment by someguy20336** [comment]
My guess is that the issue is in the ```NetFrameworkWorkspaceBuilder```.  I am probably adding duplicate references, but not sure why - MsBuild should be passing me the references anyway.  Fix is probably to ensure no duplicates are added there.

**Comment by someguy20336** [comment]
yep, turns out we had two of the same project references in the csproj for who knows what reason.  Closing as not an issue.  Probably SVN merge issue.
